//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dpcTrackr
{
    using System;
    using System.Collections.Generic;
    
    public partial class LABOUR_REQUIREMENT
    {
        public int ID { get; set; }
        public int prodTeamID { get; set; }
        public int taskID { get; set; }
        public Nullable<System.DateTime> lreqEstDate { get; set; }
        public Nullable<short> lreqEstHours { get; set; }
        public Nullable<System.DateTime> lreqActDate { get; set; }
        public Nullable<short> lreqActHours { get; set; }
        public string lreqComments { get; set; }
    
        public virtual PROD_TEAM PROD_TEAM { get; set; }
        public virtual TASK TASK { get; set; }
    }
}
