//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dpcTrackr
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL
    {
        public MATERIAL()
        {
            this.INVENTORies = new HashSet<INVENTORY>();
        }
    
        public int ID { get; set; }
        public string matDesc { get; set; }
        public string matType { get; set; }
    
        public virtual ICollection<INVENTORY> INVENTORies { get; set; }
    }
}
