//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dpcTrackr
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_TEAM
    {
        public PROD_TEAM()
        {
            this.LABOUR_REQUIREMENT = new HashSet<LABOUR_REQUIREMENT>();
        }
    
        public int ID { get; set; }
        public int projectID { get; set; }
        public int workerID { get; set; }
        public string teamPhaseIn { get; set; }
    
        public virtual ICollection<LABOUR_REQUIREMENT> LABOUR_REQUIREMENT { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual WORKER WORKER { get; set; }
    }
}
