//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dpcTrackr
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT
    {
        public PROJECT()
        {
            this.LABOUR_SUMMARY = new HashSet<LABOUR_SUMMARY>();
            this.MATERIAL_REQ = new HashSet<MATERIAL_REQ>();
            this.PROD_TEAM = new HashSet<PROD_TEAM>();
            this.PROD_TOOL = new HashSet<PROD_TOOL>();
        }
    
        public int ID { get; set; }
        public string projName { get; set; }
        public string projSite { get; set; }
        public System.DateTime projBidDate { get; set; }
        public string projEstStart { get; set; }
        public string projEstEnd { get; set; }
        public string projActStart { get; set; }
        public string projActEnd { get; set; }
        public string projEstCost { get; set; }
        public string projActCost { get; set; }
        public Nullable<bool> projBidCustAccept { get; set; }
        public Nullable<bool> projBidMgmtAccept { get; set; }
        public string projCurrentPhase { get; set; }
        public Nullable<bool> projIsFlagged { get; set; }
        public int clientID { get; set; }
        public int designerID { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual ICollection<LABOUR_SUMMARY> LABOUR_SUMMARY { get; set; }
        public virtual ICollection<MATERIAL_REQ> MATERIAL_REQ { get; set; }
        public virtual ICollection<PROD_TEAM> PROD_TEAM { get; set; }
        public virtual ICollection<PROD_TOOL> PROD_TOOL { get; set; }
        public virtual WORKER WORKER { get; set; }
    }
}
