//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dpcTrackr
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKER
    {
        public WORKER()
        {
            this.PROD_TEAM = new HashSet<PROD_TEAM>();
            this.PROJECTs = new HashSet<PROJECT>();
        }
    
        public int ID { get; set; }
        public string wrkFName { get; set; }
        public string wrkLName { get; set; }
        public int wrkTypeID { get; set; }
    
        public virtual ICollection<PROD_TEAM> PROD_TEAM { get; set; }
        public virtual ICollection<PROJECT> PROJECTs { get; set; }
        public virtual WORKER_TYPE WORKER_TYPE { get; set; }
    }
}
